version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Build phase..."
      # If you have a build script like React/Next.js, uncomment:
      # - npm run build

  post_build:
    commands:
      - echo "Packaging application for Elastic Beanstalk..."
      - rm -f app.zip
      - zip -r app.zip . \
          -x "node_modules/*" \
          -x "*.git*" \
          -x ".git/*" \
          -x "app.zip"

artifacts:
  files:
    - app.zip
